version: "3"
services:
  go-app:
    build: ./go-app
    ports: 
        - "3001:3001"
    depends_on:
        - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
    mongodb_data_container: